# Read the documentation: https://symfony.com/doc/master/bundles/FOSRestBundle/index.html
fos_rest:
  view:
    view_response_listener: force
    formats:
      json: true
  format_listener:
    rules:
      - { priorities: ['json'], fallback_format: json, prefer_extension: false }
  serializer:
    serialize_null: true
  exception:
    enabled: true
    messages:
      Symfony\Component\HttpKernel\Exception\BadRequestHttpException: true
