monolog:
  channels:
    - database
    - transport
    - document
    - sync
    - artego
    - auth
    - emp_client
    - ert
    - admin_review
    - elastica
    - monitoring
  handlers:
    main:
      type: fingers_crossed
      action_level: debug
      handler: nested
      excluded_http_codes: [404, 405]
      buffer_size: 50 # How many messages should be saved? Prevent memory leaks
      formatter: 'monolog.formatter.json'
      channels: ["!database"]
    nested:
      type: stream
      path: "php://stdout"
      level: debug
      channels: ["!database"]
      formatter: 'monolog.formatter.json'
    console:
      type: console
      process_psr_3_messages: false
      channels: ["!event", "!doctrine", "!database"]
      formatter: 'monolog.formatter.json'
    database:
      level: debug
      type: stream
      path: "php://stdout"
      formatter: 'monolog.formatter.json'
      channels: ["database"]
    elastica:
      level: debug
      type: stream
      formatter: 'monolog.formatter.json'
      channels: [ "elastica" ]
